### ISSUE TITLE
sample may fail because Math.random() may return zero and the result is passed to Math.log()

### ISSUE THREAD

**Issue by espendk** [axelpale/poisson-process#5]
In sample.js there is the following code:

https://github.com/axelpale/poisson-process/blob/73a43187b1a3bc08db8628200b6ab3ca937634d2/lib/sample.js#L8

This will fail if `Math.random()` returns zero, which it can: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

This may be solved by doing the following instead:

```JavaScript
  return -Math.log(1 - Math.random()) * mean;
```

**Comment by axelpale** [comment]
Oh, great catch! Of course changes of 0 are miniscule but indeed possible.

Out of curiosity, how possible is it? Assuming 64-bit [double precision floating point](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#JavaScript) where the fraction part takes 52 bits, `Math.random()` has 2^52 possible outcomes. Therefore we can assume probability for the zero to be 1 / 2^52. Assume 1000 samples a second, statistically you get about one zero each 140 000 years (tries times probability: `(1000 * 60 * 60 * 24 * 365 * 140000) / 2^52 = 0.980...`).

The prob sounds low but it only assumes a single process. With possible wide adoption and under-the-hood reach of 1 million users that could mean multiple zeroes per year. Not so impossible after all!

Thank you for finding and reporting this. You have a truly sharp eye. I will do the update soon.

**Comment by axelpale** [comment]
I just published v1.0.1 with the fix. Thank you!

**Comment by espendk** [comment]
Np! That was quick :-)
